server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://192.168.78.200:3306/micromall?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: mysql
    password: mysql
    druid:
      initial-size: 5 #初始化连接数量
      min-idle: 10 #空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #排除这些url的统计
      stat-view-servlet: #
        login-username: druid
        login-password: druid
  redis:
    host: 192.168.78.200
    port: 6379
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:com/**/mapper/*.xml
#自定义redis键值
redis:
  key:
    prefix:
      otpCode: "member:otpCode"
    expire:
      otpCode: 60 #秒